blueprint:
  name: 'Smart Presence Lights based on ambient luminance'
  description: >
    Liga a luz ao detectar presença ou acionamento manual e inicia um timer.
    Reinicia o timer a cada presença ou acionamento manual.
    Desliga automaticamente ao fim do tempo.
  domain: automation

  input:
    presence_sensor:
      name: Sensor de presença
      selector:
        entity:
          domain:
            - binary_sensor

    target_switch:
      name: Luz / Interruptor
      selector:
        entity:
          domain:
            - light
            - switch

    countdown_time:
      name: 'Tempo até desligar - ex: 60s, 3min, 15min'
      selector:
        duration:

    only_if_dark:
      name: 'Opcional - Só ligar se estiver escuro'
      default: false
      selector:
        boolean: {}

    lux_sensor:
      name: 'Opcional - Sensor de luminosidade'
      default: null
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    lux_threshold:
      name: 'Limite máximo de luminosidade (lx)'
      description: Se o sensor medir menos que esse valor, o ambiente será considerado escuro
      default: 15
      selector:
        number:
          min: 1
          max: 200
          unit_of_measurement: 1x
          mode: slider

mode: restart

trigger:
  - id: presence
    platform: state
    entity_id: !input presence_sensor
    to: "on"

  - id: manual_on
    platform: state
    entity_id: !input target_switch
    to: "on"

condition: >
  {{ not (
    trigger.id == 'presence'
    and (iif(
          !input only_if_dark,
          false,
          (
            not (states[inputs.lux_sensor] is defined)
            or (states[inputs.lux_sensor].state | float < (inputs.lux_threshold | float))
          )
        ) == false
      )
  ) }}

action:
  - service: homeassistant.turn_on
    target:
      entity_id: !input target_switch

  - delay: "{{ input.countdown_time }}"

  - service: homeassistant.turn_off
    target:
      entity_id: !input target_switch
