blueprint:
  name: Sensor Light Basic
  description: Aciona interruptores por sensor de presença, condicionado a limite de luminosidade (opcional), faixa de horários e dias da semana (opcionais).
  domain: automation
  input:
    presence_sensor:
      name: Sensor de Presença
      selector:
        entity:
          domain:
            - binary_sensor

    target_lights:
      name: Switches a serem acionados
      selector:
        target:
          entity:
            domain: switch

    countdown_time:
      name: Tempo para desligar (segundos)
      default: 60
      selector:
        number:
          min: 1
          max: 1800
          step: 5
          mode: slider

    only_if_dark:
      name: Habilitar conforme limite de luminosidade?
      default: false
      selector:
        boolean: {}

    lux_sensor:
      name: Sensor de luminosidade (opcional)
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    lux_limit:
      name: Limite máximo de lux para ativação (opcional)
      default: 10
      selector:
        number:
          min: 0
          max: 200
          step: 5
          mode: slider

    start_time:
      name: Hora inicial (opcional)
      description: Se vazio, funciona o dia todo.
      default: ""
      selector:
        time: {}

    end_time:
      name: Hora final (opcional)
      description: Se vazio, funciona o dia todo.
      default: ""
      selector:
        time: {}

    allowed_days:
      name: Dias permitidos (opcional)
      description: Se nenhuma opção for marcada, funcionará todos os dias.
      default: []
      selector:
        select:
          options:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
          multiple: true

mode: restart

trigger:
  - platform: state
    entity_id: !input presence_sensor
    to: "on"

  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    for:
      seconds: !input countdown_time

condition: []

action:
  - choose:
      # ---------------------------
      # SENSOR LIGOU
      # ---------------------------
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: "on"

          # Dias da semana (opcional)
          - condition: template
            value_template: >
              {% set days = iinput.allowed_days %}
              {% if days == [] %}
                true
              {% else %}
                {{ now().strftime('%A') in days }}
              {% endif %}

          # Verificação de horário (opcional)
          - condition: template
            value_template: >
              {% set start = iinput.start_time %}
              {% set end = iinput.end_time %}
              {% if start == "" or end == "" %}
                true
              {% else %}
                {{ start < now().strftime('%H:%M:%S') < end }}
              {% endif %}

          # Verificação de lux (opcional)
          - condition: template
            value_template: >
              {% if iinput.only_if_dark == false %}
                true
              {% else %}
                {% if iinput.lux_sensor == "" %}
                  true
                {% else %}
                  {{ states(iinput.lux_sensor) | float(0) <= (iinput.lux_limit | float) }}
                {% endif %}
              {% endif %}
        sequence:
          - service: switch.turn_on
            target: !input target_lights

    # ---------------------------
    # SENSOR DESLIGOU
    # ---------------------------
    default:
      - service: switch.turn_off
        target: !input target_lights
